import type { Metadata } from "next";
import { SessionProviderProm } from "@/context/useSessionProm";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import NavbarProm from "@/components/navbarProm";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProviderProm>
      <NavbarProm />
      {children}
      <ToastContainer
        draggable
        closeOnClick
        autoClose={5000}
        theme="dark"
        position="bottom-right"
      />
    </SessionProviderProm>
  );
}
