import type { Metadata } from "next";
import { SessionProviderUser } from "@/context/useSessionUser";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import NavbarUser from "@/components/navbarUser";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProviderUser>
      <NavbarUser />
      {children}
      <ToastContainer
        draggable
        closeOnClick
        autoClose={5000}
        theme="dark"
        position="bottom-right"
      />
    </SessionProviderUser>
  );
}
